# Generated by Django 2.2 on 2020-01-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ath_first_name', models.CharField(max_length=255)),
                ('ath_last_name', models.CharField(max_length=255)),
                ('sport', models.CharField(choices=[('Select-Sport', 'Select-Sport'), ('Archery', 'Archery'), ('B-Basketball', 'B-Basketball'), ('G-Basketball', 'G-Basketball'), ('Baseball', 'Baseball'), ('B-XCountry', 'B-XCountry'), ('G-XCountry', 'G-XCountry'), ('Football', 'Football'), ('Golf', 'Golf'), ('Gymnastics', 'Gymnastics'), ('B-Soccer', 'B-Soccer'), ('G-Soccer', 'G-Soccer'), ('Softball', 'Softball'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('B-Track', 'B-Track'), ('G-Track', 'G-Track'), ('Volleyball', 'Volleyball'), ('Wrestling', 'Wrestling')], default='', max_length=45)),
                ('injured', models.BooleanField(default='True')),
                ('injury', models.CharField(choices=[('Select-Injury', 'Select-Injury'), ('Head', 'Head'), ('Face', 'Face'), ('Neck', 'Neck'), ('Shoulder', 'Shoulder'), ('Arm', 'Arm'), ('Elbow', 'Elbow'), ('Wrist', 'Wrist'), ('Hand', 'Hand'), ('Finger', 'Finger'), ('Chest', 'Chest'), ('Abdomen', 'Abdomen'), ('Back', 'Back'), ('Hip', 'Hip'), ('Thigh', 'Thigh'), ('Knee', 'Knee'), ('Shin_Calf', 'Shin_Calf'), ('Ankle', 'Ankle'), ('Foot', 'Foot'), ('Toe', 'Toe')], default='', max_length=45)),
                ('desc', models.TextField()),
                ('inj_date', models.DateTimeField(null=True)),
                ('poss_return', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=45)),
                ('user_level', models.CharField(choices=[('Coach', 'Coach'), ('Admin', 'Admin'), ('S_Admin', 'S_Admin')], default='coach', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='injury_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='injury_app.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='injury_app.User')),
            ],
        ),
    ]
