# Generated by Django 2.2 on 2020-01-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injury_app', '0006_auto_20200130_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='inj_date',
            field=models.DateTimeField(default='0000/00/00', null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='poss_return',
            field=models.DateTimeField(default='0000/00/00', null=True),
        ),
    ]
