# Generated by Django 2.2 on 2020-01-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injury_app', '0008_auto_20200130_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='injury',
            field=models.CharField(choices=[('Head', 'Head'), ('Face', 'Face'), ('Neck', 'Neck'), ('Shoulder', 'Shoulder'), ('Arm', 'Arm'), ('Elbow', 'Elbow'), ('Wrist', 'Wrist'), ('Hand', 'Hand'), ('Finger', 'Finger'), ('Chest', 'Chest'), ('Abdomen', 'Abdomen'), ('Back', 'Back'), ('Hip', 'Hip'), ('Thigh', 'Thigh'), ('Knee', 'Knee'), ('Shin_Calf', 'Shin_Calf'), ('Ankle', 'Ankle'), ('Foot', 'Foot'), ('Toe', 'Toe')], max_length=45),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sport',
            field=models.CharField(choices=[('Archery', 'Archery'), ('B-Basketball', 'B-Basketball'), ('G-Basketball', 'G-Basketball'), ('Baseball', 'Baseball'), ('B-XCountry', 'B-XCountry'), ('G-XCountry', 'G-XCountry'), ('Football', 'Football'), ('Golf', 'Golf'), ('Gymnastics', 'Gymnastics'), ('B-Soccer', 'B-Soccer'), ('G-Soccer', 'G-Soccer'), ('Softball', 'Softball'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('B-Track', 'B-Track'), ('G-Track', 'G-Track'), ('Volleyball', 'Volleyball'), ('Wrestling', 'Wrestling')], max_length=45),
        ),
    ]
